Repository timelygator/TimelyGator, pull requests merged in 2025-03, with the labels that each got.

#56 Create classes.go and add ClassItem and DefaultClasses for classification handling
  server/client/classes.go
Labels: enhancement, backend

#57 Add example query handling with parameter structures
  server/client/queries.go
Labels: enhancement, backend

#58 Add example query handling with parameter structures
  server/client/queries.go
Labels: enhancement, backend

#62 Implement single instance lock mechanism
  server/client/queries.go
  server/client/singleinstance.go
Labels: enhancement, backend

#67 Implement CLI for Client
  server/client/main/main.go
Labels: enhancement, backend

#72 Add API Templates & Cypress Unit Tests for Components
  web-ui/cypress.config.js
  web-ui/cypress/fixtures/example.json
  web-ui/cypress/support/commands.js
  web-ui/cypress/support/component-index.html
  web-ui/cypress/support/component.js
  web-ui/cypress/support/e2e.js
  web-ui/package-lock.json
  web-ui/package.json
  web-ui/src/components/analytics/OverviewCards.cy.jsx
  web-ui/src/components/analytics/actualChart.cy.jsx
  web-ui/src/components/common/Header.cy.jsx
  web-ui/src/components/common/Sidebar.cy.jsx
  web-ui/src/components/common/Sidebar.jsx
  web-ui/src/components/common/StatCard.cy.jsx
  web-ui/src/components/common/StatCard.jsx
  web-ui/src/components/overview/CategoryDistributionChart.cy.jsx
  web-ui/src/components/overview/CategoryDistributionChart.jsx
  web-ui/src/components/overview/UsageOverviewChart.cy.jsx
  web-ui/src/components/overview/UsageOverviewChart.jsx
  web-ui/src/components/overview/WebsiteDis.jsx
  web-ui/src/components/overview/WebsiteDisWebsiteDistributionChart.cy.jsx
  web-ui/src/components/settings/ConnectedAccounts.cy.jsx
  web-ui/src/components/settings/DangerZone.cy.jsx
  web-ui/src/components/settings/Notifications.cy.jsx
  web-ui/src/components/settings/Profile.cy.jsx
  web-ui/src/components/settings/Profile.jsx
  web-ui/src/components/settings/Security.cy.jsx
  web-ui/src/components/settings/Security.jsx
  web-ui/src/components/settings/SettingSection.cy.jsx
  web-ui/src/components/settings/ToggleSwitch.cy.jsx
  web-ui/src/components/settings/ToggleSwitch.jsx
  web-ui/src/components/tabs/TabTable.cy.jsx
  web-ui/src/components/tabs/TabTable.jsx
  web-ui/src/pages/AnalyticsPage.cy.jsx
  web-ui/src/pages/AnalyticsPage.jsx
  web-ui/src/pages/OverviewPage.cy.jsx
  web-ui/src/pages/OverviewPage.jsx
  web-ui/src/pages/SettingsPage.cy.jsx
  web-ui/src/pages/TabsPage.cy.jsx
  web-ui/src/pages/TabsPage.jsx
Labels: frontend, sprint-2

#78 AFKWatcher connections with client
  server/observers/afk-observer/afk.go
  server/observers/afk-observer/config.go
Labels: enhancement, backend

#83 Add Unit Tests for TimelyGatorClient
  server/client/client_test.go
Labels: backend

#86 Update Sprint2.md
  docs/sprint/Sprint2.md
Labels: documentation
